### ISSUE TITLE
Losing up to 50% of my recording

### ISSUE THREAD

**Issue by pjlworld** [thetarkus/WebMCam#20]
Hi, I have a high performing PC, and I try to record some clips from dota 2, not anything long, ~30sec vids.  The software is functionally so awesome, but a lot of the time, I lose up to 50% of my recording and it's rather frustrating.  Could this be troubleshooted somehow?

**Comment by inexist3nce** [comment]
This happened to me too, but I've noticed its only if I record at a high (+30) framerate.

**Comment by thetarkus** [comment]
The speed at which frames can be saved is highly dependent on your storage medium. Fast SSDs and HDDs will prevail. Also, be aware that higher resolution and higher framerate take huge tolls in performance of WebMCam.

Please try WebMCam v2.0 and see if that solves your issue. Create a new issue if it has not.

Thanks.

**Comment by Cyan101** [comment]
Would perhaps storing the screenshots and stuff in RAM work? a lot of high end PC's have 16/32GB's of RAM that would easily be able to hold long recordings and wouldnt be limited by the slow speeds of HDD 's and SSD's

**Comment by thetarkus** [comment]
@Cyan101 Yes. This was originally how WebMCam stored the image data until the disk was available to write the next frame. I ran into problems of running out of RAM (16GB) because the disk was unable to keep up with the asynchronous saving and then the framerate would tank. If my mind serves me correctly, each loseless frame was roughly 4MB.

If anyone wants to take a crack at getting it to work properly, I do accept pull requests.
