### ISSUE TITLE
Recordings are lower quality than before

### ISSUE THREAD

**Issue by pjlworld** [theTarkus/WebMCam#27]
Hello, big fan of webmcam.  Thanks for the new release, I thought maybe you had given up on the project.  I'm glad you didn't.

Since its new release (2.0 and after), I've noticed a huge drop in its recording quality.   The 2.04 feels a little less stable than 2.0.  When I record, there's more frame lag in 2.0.3 than 2.0.0.  Link below is are an example:

2.0.0:
http://webmshare.com/99Z8W
2.0.3:
http://webmshare.com/Gyd8a

Both are recorded with 30fps, with nothing in the background with everything being ran on SSD and good pc (I can send dxdiag if it helps? no idea how these things work soz).  Before it would give me really nice quality, smooth recording with higher file size.  Now, it's a lot smaller but worse quality.  

I was also wondering if there's a better way to contact you other than github.  Thanks again for your work.

**Comment by thetarkus** [comment]
I've looked into this and I believe that the problem you are having (with the stutter) is in fact FFmpeg trying to compensate for missing frames to keep a consistent 30fps.

[v2.1.0 https://github.com/thetarkus/WebMCam/releases/tag/210]
To combat this, in v2.1.0 I've tweaked the FFmpeg arguments to use the average fps as output instead of forcing FFmpeg to duplicate frames to achieve the desired framerate. This included with the new, more accurate, timers should (and in my case, have) give you higher framerates and better results.

If you are also mentioning the quality of the video, you can up the bitrate in the FFmpeg arguments in options by changing the area by "-b:v 2M" and changing the "2."

Another way to contact me is through Telegram (telegram.me), but I'll only put my username here if you want it.

**Comment by theTarkus** [comment]
This should be solved with v2.2.0. If you're still having a problem re-open or comment again on this issue.
