### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by blurymind** [theTarkus/WebMCam#33]
is this possible to compile under linux?

**Comment by theTarkus** [comment]
Unfortunately no. One day I may find the time to replicate the core functionality in a more cross-platform language/framework; or perhaps Microsoft will finish porting the .NET core and stack and I'll be able to change the way it captures and recreate the forms. Whichever comes first.

**Comment by sayboltm** [comment]
Since you like linux so much, any update on this?  I see Microsoft has since declared it's allegiance to open-source, and Windows 10 should be the last windows ever, and embrace this paradigm.  I have since given up hope.  This is still the #1 tool for this, but only on windows :( 

Android would be cool too, but I'd expect that to be very different. 

Thanks for your hard work bringing this feature to Windows when Microsoft would rather delete parts of the control panel at random, and become an app pusher, instead of doing things that made Windows popular and provided real value-add features and reasons to update to the next one.
