### ISSUE TITLE
Can't delete frames when Capture Audio is checked

### ISSUE THREAD

**Issue by Volpi** [theTarkus/WebMCam#34]
Title. At post-recording screen, you can delete individual or multiple frames of the recording. Not the case if Capture Audio is checked, it just ignores both the Del key and right click context button.

Thanks for the tool, by the way! Just the way it should be, simple and functional.

**Comment by theTarkus** [comment]
The reasoning behind this is that if you delete a frame then your video gets shorter than the audio track. If the tracks aren't the same length then you get either: a stretched out video file with audio, or an out of sync video/audio file. This can't be fixed with the current method of audio and video capture.
