### ISSUE TITLE
Icon change

### ISSUE THREAD

**Issue by dannyblank** [thetarkus/WebMCam#40]
The Icon is a firerune from Runescape. While cool, it would be nice if it was more representative like a camera or a lense.

e.g. http://flaticons.net/customize.php?dir=Gadgets&icon=Camera-01.png

**Comment by theTarkus** [comment]
A camera icon on a rune would be hilarious

**Comment by dannyblank** [comment]
![webmcamicon](https://cloud.githubusercontent.com/assets/20598281/17477744/e1c3a782-5d5e-11e6-8015-789113f43415.jpg)

I got you covered bro, I'm not sure why but Github wouldn't let me upload the zip file even though it was an allowed format. Rename the extension from .jpg to .zip to access the PSD and .Icon file

**Comment by dannyblank** [comment]
This is what the above Icon looks like, the PSD file has it split into layers if you want to edit colours or what not.
![what the icon looks like](https://cloud.githubusercontent.com/assets/20598281/17477789/2426a6b0-5d5f-11e6-959b-19957ca4be1e.jpg)

**Comment by thetarkus** [comment]
Thinking about this, we can't have a square symbol over an imperfect circlish shape... I think it'd be better off with a real camera to show what it actually does like you said earlier.

http://flaticons.net/customize.php?dir=Gadgets&icon=Camera-01.png
I don't like this particular one, in fact, I downright hate it. Something with the lens bothers me.

I like the ones like these:
https://ewebdesign.com/wp-content/uploads/2013/10/camera5.jpg
https://d13yacurqjgara.cloudfront.net/users/227692/screenshots/1408661/dribbble-flat-camera_1x.jpg
http://icons.iconarchive.com/icons/designbolts/free-multimedia/1024/Dslr-Camera-icon.png
http://icons.iconarchive.com/icons/martz90/circle/512/camera-icon.png

I like the first two since they're square with rounded corners and I think they'd fit nicely into the taskbar.
What do you think? Opinions/objections?

**Comment by altbdoor** [comment]
Hey @thetarkus, firstly, thank you very much for this tool. Been very handy in my project in describing situations to clients.

Secondly, I thought I'd take a shot at making a *tasteful one in the Runescape style*. Basically I took the [fourth image](http://icons.iconarchive.com/icons/martz90/circle/512/camera-icon.png) from your list, changed the colors to red, merged it with a [Minecraft grass texture](http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1226537-128x-1-4-runescape-hd-texture-pack-wip), and overlay it on a pure essence.

Sorry its raster though. Have no experience in vector. Cheers.

![capture](https://cloud.githubusercontent.com/assets/3540471/17540853/8724711e-5eec-11e6-8333-50accbb93ff5.png)

**Comment by thetarkus** [comment]
@altbdoor I really like what you did with the Minecraft grass texture but the blurred outline and non-circular shape of the high-detailed pure essence is killing me.

Nonetheless, I've had an epiphany: we go modern (flat) but keep to our roots.
I've created two icons using ![this tool](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.space.trim=0&foreground.space.pad=0.25&foreground.clipart=res%2Fclipart%2Ficons%2Fav_videocam.svg&foreColor=ff4a40%2C100&crop=1&backgroundShape=circle&backColor=eaeaea%2C100&effects=none).

I call this work of art: Modern rune.
![image1](https://i.imgur.com/9u2iq7J.png)
![image2](https://i.imgur.com/PtiaOuW.png)

Opinions/objections?

**Comment by altbdoor** [comment]
@thetarkus haha understood :-)

The modern rune looks a lot cleaner and polished!
